### ISSUE TITLE
Working failed with CJK characters

### ISSUE THREAD

**Issue by absszero** [attilammagyar/html-filter#2]
```php
$html = '格萊美紅毯大戰誰是贏家';
$config = new \AthosHun\HTMLFilter\Configuration();
$filter = new \AthosHun\HTMLFilter\HTMLFilter();

$filter_html = $filter->filter($config, $html);
var_dump( $filter_html );exit;
// $filter_html is not equal to $html

**Comment by attilammagyar** [comment]
Thanks for the bug report, I'm going to look after it in a few days.

**Comment by attilammagyar** [comment]
It should work now (v2.0.3). Also, v2.0.4 specifies how `HTMLFilter` should handle invalid UTF-8, but that one requires `ext-mbstring` to be present (which is the case most of the time as far as I know, but to be on the safe side, I did that change in a different version).
